collections:
- name: redhat.openshift
- name: redhat.openshift_virtualization
- name: kubernetes.core
- name: redhat.rhel_system_roles
- name: community.general
roles:
- name: RedHatOfficial.rhel9_stig
