- hosts: localhost
  tasks:
  - name: Create project
    redhat.openshift.k8s:
      state: present
      definition:
        apiVersion: project.openshift.io/v1
        kind: Project
        metadata:
          name: virtdemo
  
  - name: Create RHEL virtual machine
    redhat.openshift_virtualization.kubevirt_vm:
      state: present
      name: rheldemo{{ item }}
      namespace: virtdemo
      labels:
        app: httpd
        network.kubevirt.io/headlessService: headless
      instancetype:
        name: u1.medium
      preference:
        name: rhel.9
      data_volume_templates:
        - metadata:
            name: rhel9virtdemo-volume{{ item }}
          spec:
            sourceRef:
              kind: DataSource
              name: rhel9
              namespace: openshift-virtualization-os-images
            storage:
              resources: {}
      spec:
        domain:
          devices: {}
        subdomain: headless
        volumes:
          - dataVolume:
              name: rhel9virtdemo-volume{{ item }}
            name: rootdisk
          - cloudInitNoCloud:
              userData: |-
                #cloud-config
                user: cloud-user
                password: demouser
                chpasswd:
                  expire: false
                ssh_authorized_keys:
                - {{ ssh_pub }}
            name: cloudinitdisk
    loop: "{{ range(vm_count | int) | list }}"
  
  - name: Wait for last virtual machine IP to be populated
    kubernetes.core.k8s_info:
      api_version: kubevirt.io/v1
      kind: VirtualMachineInstance
      name: rheldemo{{ (vm_count | int)-1  }}
      namespace: virtdemo
    register: vmi
    retries: 60
    delay: 10
    until: (vmi.resources[0].status.interfaces[0]['ipAddress'] | default('')) | length > 0