- hosts: localhost
  tasks: 
  - name: use subscription manager to register rhel host
    community.general.redhat_subscription:
      activationkey: "{{ activationkey }}"
      org_id: "{{ org_id }}"
      state: present
    become: true
