- hosts: namespace_virtdemo
  tasks: 
  - name: use subscription manager to register rhel host
    # ansible.builtin.command: subscription-manager register
    #   --org {{ org_id }} 
    #   --activationkey {{ activationkey }}
    community.general.redhat_subscription:
      activationkey: "{{ activationkey }}"
      org_id: "{{ org_id }}"
      pool: "^Red Hat Enterprise Linux Server$"
      state: present
    become: true

