- hosts: namespace_virtdemo
  tasks: 
  - name: use subscription manager to register rhel host
    ansible.builtin.redhat_subscription:
      activationkey: "{{ activationkey }}"
      org_id: "{{ org_id }}"
      state: present
