- hosts: namespace_virtdemo
  tasks: 
  - name: use subscription manager to register rhel host
    
  - name: rhel system role
    ansible.builtin.redhat_subscription:
      activationkey: 
      org_id: 
    redhat.rhel_system_roles.redhat_subscription:
      activationkey: "{{ activationkey }}"
      org_id: "{{ org_id }}"
      state: present
